apiVersion: v1
kind: ConfigMap
metadata:
  name: book-service-config
  namespace: microservices
data:
  DATASOURCE_URL: "jdbc:postgresql://postgres-book:5432/booking-db"
  DATASOURCE_USER: "postgres"
  BOOK_SERVICE_PORT: "8100"
  EXCHANGE_SERVICE_URL: "http://exchange-service:8001"

