spring:
  application:
    name: spring-cloud-api-gateway

  #   Alternativa ao uso da Classe ApiGatewayConfig para configuração de rotas do gateway,
  #  é possível utilizar o arquivo application.yaml, como mostrado abaixo:
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: book-service
              uri: lb://book-service
              predicates:
                - Path=/book-service/**
            - id: exchange-service
              uri: lb://exchange-service
              predicates:
                - Path=/exchange-service/**
management:
  tracing:
    sampling:
      # Recomendado 0.05 em prod
      probability: 1.0
    export:
      zipkin:
        endpoint: ${MANAGEMENT_TRACING_EXPORT_ZIPKIN_ENDPOINT:http://zipkin:9411}
  endpoint:
    gateway:
      access: unrestricted
  endpoints:
    web:
      exposure:
        include: gateway
springdoc:
  swagger-ui:
    urls:
      - name: book-service
        url: /book-service/v3/api/docs
      - name: exchange-service
        url: /exchange-service/v3/api/docs
server:
  port: 8765
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://spring-eureka-naming-server:8761/eureka}
