apiVersion: v1
kind: Service
metadata:
  name: exchange-service
  namespace: microservices
spec:
  type: LoadBalancer
  selector:
    app: exchange-service
  ports:
    - port: 8000
      targetPort: 8000
