name: CI Booking service

on:
  push:
    branches: [ "master" ]
    paths:
      - 'book-service/**'
  workflow_dispatch:

jobs:
  call-template:
    # Chama o arquivo base que criamos acima
    uses: ./.github/workflows/template-docker-image-push.yml
    # Passa as informações específicas deste serviço
    with:
      working_directory: './book-service'
      image_name: 'book-service'
    # Repassa os secrets do repositório para o template
    secrets:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_ACCESS_TOKEN: ${{ secrets.DOCKER_ACCESS_TOKEN }}