name: CI Exchange Service

on:
  push:
    branches: [ "master" ]
    paths:
      - 'exchange-service/**'
  workflow_dispatch:

jobs:
  call-template:
    permissions:
      id-token: write
      contents: read
    # Chama o arquivo base que criamos acima
    uses: ./.github/workflows/template-ci-cd.yml
    # Passa as informações específicas deste serviço
    with:
      working_directory: './exchange-service'
      image_name: 'exchange-service'
      manifests_path: 'exchange-service/k8s'
    # Repassa os secrets do repositório para o template
    secrets:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_ACCESS_TOKEN: ${{ secrets.DOCKER_ACCESS_TOKEN }}
      EXCHANGE_DATASOURCE_URL: ${{ secrets.EXCHANGE_DATASOURCE_URL }}
      BOOK_DATASOURCE_URL: ${{ secrets.BOOK_DATASOURCE_URL }}
      DATASOURCE_PASSWORD: ${{ secrets.DATASOURCE_PASSWORD }}
      DATASOURCE_USERNAME: ${{ secrets.DATASOURCE_USERNAME }}
      EXCHANGE_DATASOURCE_URL_TEST: ${{ secrets.EXCHANGE_DATASOURCE_URL_TEST }}
      BOOK_DATASOURCE_URL_TEST: ${{ secrets.BOOK_DATASOURCE_URL_TEST }}
      DATASOURCE_USER_TEST: ${{ secrets.DATASOURCE_USER_TEST  }}
      DATASOURCE_PASSWORD_TEST: ${{ secrets.DATASOURCE_PASSWORD_TEST  }}